apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-devsecops
  labels:
    app: enterprise-devsecops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: enterprise-devsecops

  template:
    metadata:
      labels:
        app: enterprise-devsecops

    spec:
      containers:
      - name: enterprise-devsecops

        image: revanth76/enterprise-devsecops:1.0.0

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"